'use client';

import { useChat } from '@ai-sdk/react';
import { useState, useEffect, useContext } from 'react';
import { useAdContext } from "../../lib/Allcontext" // Updated import
import ModelViewer from '../../components/modelviewer';
import { getContract } from '../../lib/nftContract';
import { BrowserProvider } from 'ethers';
import { 
  Send, 
  Loader2, 
  CheckCircle, 
  AlertCircle,
  User,
  Menu,
  Home,
  MessageSquare,
  X,
  Sparkles,
  Settings2,
  TrendingUp,
  Target,
  Zap,
  Image as ImageIcon,
  Video,
  Box,
  Music,
  Star,
  ExternalLink
} from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { ScrollArea } from '../../components/ui/scroll-area';
import { DefaultChatTransport } from 'ai';
/* ------------------------------------------------------------------ */
/*  1.  Minting helpers (unchanged)                                   */
/* ------------------------------------------------------------------ */
type MintStates = Record<string, { status: 'idle' | 'minting' | 'minted' | 'error'; txHash?: string; error?: string }>;
export default function MainT() {
  const [input, setInput] = useState('');
  const [mintingStates, setMintingStates] = useState<MintStates>({});
  /*  ↓  grab the credentials from context  ↓  */
 const { googleAds } = useAdContext() // Using the new AdContext

  const { messages, sendMessage } = useChat({ 
    /*  pass credentials to the backend ONLY when we actually call the tool  */
   
    prepareSendMessagesRequest({ messages, body }) {
  const packet = {
    ...body, // headers, method, etc.
    body: {
      customerId: googleAds.customerId,
      refreshToken: googleAds.refreshToken,
      managerId: googleAds.managerId,
      ...body?.body, // merge any other props you may add later
    },
  };
  console.log('[useChat] outgoing body:', packet.body);
  return packet;
},
    onFinish: (message) => {
      console.log('Message finished:', message);
      message.parts.forEach((part, index) => {
        if (part.type.includes('tool-')) {
          console.log(`Part ${index}:`, part);
        }
      });
    }
  });

  /* ------------------------------------------------------------------ */
  /*  2.  Mint content (unchanged)                                     */
  /* ------------------------------------------------------------------ */
  const mintContent = async (contentType: string, contentData: any, partIndex: number, messageId: string) => {
    const mintKey = `${messageId}-${partIndex}`;
    setMintingStates(prev => ({ ...prev, [mintKey]: { status: 'minting' } }));
    try {
      const metadata = {
        name: `${contentType} Creation`,
        description: `AI-generated ${contentType}`,
        attributes: [
          { trait_type: "Type", value: contentType },
          { trait_type: "Generated By", value: "AI Assistant" }
        ],
        ...(contentType === 'image' && contentData.imageUrl && { image: contentData.imageUrl }),
        ...(contentType === 'video' && {
          animation_url: contentData.videoUrl,
          image: contentData.coverUrl || '',
        }),
        ...(contentType === '3dmodel' && {
          animation_url: contentData.modelFileUrl,
          image: contentData.videoUrl || '',
        }),
        ...(contentType === 'song' && {
          animation_url: contentData.audioUrl,
          image: contentData.imageUrl || '',
          ...(contentData.title && { name: contentData.title }),
        }),
      };

      const res = await fetch('/api/uploadMetadata', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(metadata),
      });
      if (!res.ok) throw new Error('Failed to upload metadata');
      const { uri } = await res.json();

      const provider = new BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const nft = getContract(signer);
      const tx = await nft.mint(uri);
      await tx.wait();

      setMintingStates(prev => ({ 
        ...prev, 
        [mintKey]: { status: 'minted', txHash: tx.hash } 
      }));
      alert(`NFT minted! Tx: ${tx.hash}`);
    } catch (err: any) {
      console.error('Minting error:', err);
      setMintingStates(prev => ({ 
        ...prev, 
        [mintKey]: { status: 'error', error: err.message } 
      }));
      alert(`Minting failed: ${err.message}`);
    }
  };

  /* ------------------------------------------------------------------ */
  /*  3.  Render tool parts (unchanged)                                 */
  /* ------------------------------------------------------------------ */
  const renderToolPart = (part: any, i: number, messageId: string) => {
    const mintKey = `${messageId}-${i}`;
    const mintState = mintingStates[mintKey] || { status: 'idle' };

    if (part.type === 'text') return <span key={i}>{part.text}</span>;

    /* ----------  image  ---------- */
    if (part.type === 'tool-generateImage') {
      if (part.state === 'input-available') return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <ImageIcon size={16} />
            <span className="text-sm font-medium">Creating image...</span>
          </div>
        </div>
      );
      if (part.state === 'output-available') return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="mb-3">
            <div className="flex items-center space-x-2 text-gray-300 mb-2">
              <ImageIcon size={16} />
              <span className="text-sm font-semibold">Generated Image</span>
            </div>
            <img src={part.output.imageUrl} alt="Generated" className="w-full rounded-xl border border-gray-700/30 shadow-lg" />
          </div>
          {mintState.status === 'idle' && (
            <button onClick={() => mintContent('image', part.output, i, messageId)} className="w-full bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 py-2 px-4 rounded-xl text-sm font-medium hover:from-gray-500 hover:to-gray-600 transition-all duration-200 shadow-lg hover:shadow-gray-600/20">
              Mint as NFT
            </button>
          )}
          {mintState.status === 'minting' && (
            <div className="flex items-center justify-center space-x-2 text-gray-400 py-2">
              <Loader2 size={16} className="animate-spin" />
              <span className="text-sm">Minting in progress...</span>
            </div>
          )}
          {mintState.status === 'minted' && (
            <div className="bg-green-950/30 border border-green-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-green-400 text-sm">
                <CheckCircle size={16} />
                <span className="font-medium">NFT Minted Successfully!</span>
              </div>
              <a href={`https://etherscan.io/tx/${mintState.txHash}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center space-x-1 text-xs text-green-300 hover:text-green-200 mt-1">
                <ExternalLink size={12} />
                <span>View transaction</span>
              </a>
            </div>
          )}
          {mintState.status === 'error' && (
            <div className="bg-red-950/30 border border-red-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-red-400 text-sm">
                <AlertCircle size={16} />
                <span className="font-medium">Minting failed: {mintState.error}</span>
              </div>
            </div>
          )}
        </div>
      );
      if (part.state === 'output-error') return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>Error: {part.errorText}</span>
          </div>
        </div>
      );
      return null;
    }

    /* ----------  Google Ads tool  ---------- */
if (part.type === 'tool-googleAds') {
  switch (part.state) {
    case 'input-available':
      return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <Target size={16} />
            <span className="text-sm font-medium">Working on your campaign…</span>
          </div>
        </div>
      );
    case 'output-available':
      return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="flex items-center space-x-2 text-gray-300 mb-2">
            <Target size={16} />
            <span className="text-sm font-semibold">Campaign Result</span>
          </div>
          <pre className="text-sm text-gray-200 whitespace-pre-wrap leading-relaxed">
            {part.output.message /* the markdown you returned */}
          </pre>
          {/* Optional: show raw structured data */}
          {part.output.campaignId && (
            <div className="mt-3 text-xs text-gray-400">
              Campaign ID: <span className="font-mono">{part.output.campaignId}</span>
            </div>
          )}
        </div>
      );
    case 'output-error':
      return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>Ads Error: {part.errorText}</span>
          </div>
        </div>
      );
    default:
      return null;
  }
}

    /* ----------  video  ---------- */
    if (part.type === 'tool-generateVideo') {
      if (part.state === 'input-available') return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <Video size={16} />
            <span className="text-sm font-medium">Creating video...</span>
          </div>
        </div>
      );
      if (part.state === 'output-available') return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="mb-3">
            <div className="flex items-center space-x-2 text-gray-300 mb-2">
              <Video size={16} />
              <span className="text-sm font-semibold">Generated Video</span>
            </div>
            <div className="text-sm text-gray-400 mb-3">{part.output.description}</div>
            {part.output.coverUrl && (
              <img src={part.output.coverUrl} alt="Video preview" className="w-full rounded-xl border border-gray-700/30 shadow-lg mb-3" />
            )}
            {part.output.videoUrl && (
              <video controls className="w-full rounded-xl border border-gray-700/30 shadow-lg" poster={part.output.coverUrl}>
                <source src={part.output.videoUrl} type="video/mp4" />
                Your browser does not support the video tag.
              </video>
            )}
          </div>
          {mintState.status === 'idle' && (
            <button onClick={() => mintContent('video', part.output, i, messageId)} className="w-full bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 py-2 px-4 rounded-xl text-sm font-medium hover:from-gray-500 hover:to-gray-600 transition-all duration-200 shadow-lg hover:shadow-gray-600/20">
              Mint as NFT
            </button>
          )}
          {mintState.status === 'minting' && (
            <div className="flex items-center justify-center space-x-2 text-gray-400 py-2">
              <Loader2 size={16} className="animate-spin" />
              <span className="text-sm">Minting in progress...</span>
            </div>
          )}
          {mintState.status === 'minted' && (
            <div className="bg-green-950/30 border border-green-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-green-400 text-sm">
                <CheckCircle size={16} />
                <span className="font-medium">NFT Minted Successfully!</span>
              </div>
              <a href={`https://etherscan.io/tx/${mintState.txHash}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center space-x-1 text-xs text-green-300 hover:text-green-200 mt-1">
                <ExternalLink size={12} />
                <span>View transaction</span>
              </a>
            </div>
          )}
          {mintState.status === 'error' && (
            <div className="bg-red-950/30 border border-red-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-red-400 text-sm">
                <AlertCircle size={16} />
                <span className="font-medium">Minting failed: {mintState.error}</span>
              </div>
            </div>
          )}
        </div>
      );
      if (part.state === 'output-error') return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>Video Error: {part.errorText}</span>
          </div>
        </div>
      );
      return null;
    }

    /* ----------  3-D model  ---------- */
    if (part.type === 'tool-generate3DModel') {
      if (part.state === 'input-available') return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <Box size={16} />
            <span className="text-sm font-medium">Creating 3-D model...</span>
          </div>
        </div>
      );
      if (part.state === 'output-available') return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="mb-3">
            <div className="flex items-center space-x-2 text-gray-300 mb-2">
              <Box size={16} />
              <span className="text-sm font-semibold">Generated 3-D Model</span>
            </div>
            <div className="text-sm text-gray-400 mb-3">{part.output.description || '3-D model generated successfully'}</div>
            {part.output.modelFileUrl && (
              <div className="h-96 w-full border border-gray-700/30 rounded-xl mb-3 overflow-hidden bg-gray-900/50">
                <ModelViewer 
                  modelUrl={part.output.modelFileUrl}
                  showControls={true}
                  onLoading={(isLoading) => console.log('Loading:', isLoading)}
                  onError={(error) => console.error('Model error:', error)}
                />
              </div>
            )}
            {part.output.videoUrl && (
              <div className="mt-3">
                <div className="text-sm font-medium text-gray-300 mb-2">Preview Video:</div>
                <video controls className="w-full rounded-xl border border-gray-700/30 shadow-lg">
                  <source src={part.output.videoUrl} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              </div>
            )}
          </div>
          {mintState.status === 'idle' && (
            <button onClick={() => mintContent('3dmodel', part.output, i, messageId)} className="w-full bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 py-2 px-4 rounded-xl text-sm font-medium hover:from-gray-500 hover:to-gray-600 transition-all duration-200 shadow-lg hover:shadow-gray-600/20">
              Mint as NFT
            </button>
          )}
          {mintState.status === 'minting' && (
            <div className="flex items-center justify-center space-x-2 text-gray-400 py-2">
              <Loader2 size={16} className="animate-spin" />
              <span className="text-sm">Minting in progress...</span>
            </div>
          )}
          {mintState.status === 'minted' && (
            <div className="bg-green-950/30 border border-green-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-green-400 text-sm">
                <CheckCircle size={16} />
                <span className="font-medium">NFT Minted Successfully!</span>
              </div>
              <a href={`https://etherscan.io/tx/${mintState.txHash}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center space-x-1 text-xs text-green-300 hover:text-green-200 mt-1">
                <ExternalLink size={12} />
                <span>View transaction</span>
              </a>
            </div>
          )}
          {mintState.status === 'error' && (
            <div className="bg-red-950/30 border border-red-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-red-400 text-sm">
                <AlertCircle size={16} />
                <span className="font-medium">Minting failed: {mintState.error}</span>
              </div>
            </div>
          )}
        </div>
      );
      if (part.state === 'output-error') return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>3-D Model Error: {part.errorText}</span>
          </div>
        </div>
      );
      return null;
    }

    /* ----------  song  ---------- */
    if (part.type === 'tool-generateSong') {
      if (part.state === 'input-available') return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <Music size={16} />
            <span className="text-sm font-medium">Creating song...</span>
          </div>
        </div>
      );
      if (part.state === 'output-available') return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="mb-3">
            <div className="flex items-center space-x-2 text-gray-300 mb-2">
              <Music size={16} />
              <span className="text-sm font-semibold">{part.output.title || 'Generated Music'}</span>
            </div>
            {part.output.imageUrl && (
              <div className="mb-3">
                <img src={part.output.imageUrl} alt="Song cover" className="w-48 h-48 object-cover rounded-xl border border-gray-700/30 shadow-lg" />
              </div>
            )}
            {part.output.audioUrl ? (
              <div className="mb-3">
                <div className="text-sm font-medium text-gray-300 mb-2">Audio:</div>
                <audio controls className="w-full rounded-xl bg-gray-900/50 border border-gray-700/30">
                  <source src={part.output.audioUrl} type="audio/mpeg" />
                  <source src={part.output.audioUrl} type="audio/wav" />
                  Your browser does not support the audio element.
                </audio>
                <div className="mt-2">
                  <a href={part.output.audioUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center space-x-1 text-xs text-gray-400 hover:text-gray-300">
                    <ExternalLink size={12} />
                    <span>Download audio</span>
                  </a>
                </div>
              </div>
            ) : (
              <div className="mb-3 text-sm text-gray-500 italic">Audio is being processed... Please check back in a moment.</div>
            )}
            {part.output.videoUrl && (
              <div className="mb-3">
                <div className="text-sm font-medium text-gray-300 mb-2">Video Preview:</div>
                <video controls className="w-full rounded-xl border border-gray-700/30 shadow-lg">
                  <source src={part.output.videoUrl} type="video/mp4" />
                  Your browser does not support the video tag.
                </video>
              </div>
            )}
          </div>
          {mintState.status === 'idle' && (
            <button onClick={() => mintContent('song', part.output, i, messageId)} className="w-full bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 py-2 px-4 rounded-xl text-sm font-medium hover:from-gray-500 hover:to-gray-600 transition-all duration-200 shadow-lg hover:shadow-gray-600/20">
              Mint as NFT
            </button>
          )}
          {mintState.status === 'minting' && (
            <div className="flex items-center justify-center space-x-2 text-gray-400 py-2">
              <Loader2 size={16} className="animate-spin" />
              <span className="text-sm">Minting in progress...</span>
            </div>
          )}
          {mintState.status === 'minted' && (
            <div className="bg-green-950/30 border border-green-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-green-400 text-sm">
                <CheckCircle size={16} />
                <span className="font-medium">NFT Minted Successfully!</span>
              </div>
              <a href={`https://etherscan.io/tx/${mintState.txHash}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center space-x-1 text-xs text-green-300 hover:text-green-200 mt-1">
                <ExternalLink size={12} />
                <span>View transaction</span>
              </a>
            </div>
          )}
          {mintState.status === 'error' && (
            <div className="bg-red-950/30 border border-red-500/20 rounded-xl p-3">
              <div className="flex items-center space-x-2 text-red-400 text-sm">
                <AlertCircle size={16} />
                <span className="font-medium">Minting failed: {mintState.error}</span>
              </div>
            </div>
          )}
        </div>
      );
      if (part.state === 'output-error') return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>Song Error: {part.errorText}</span>
          </div>
        </div>
      );
      return null;
    }

    /* ----------  face-swap  ---------- */
    if (part.type === 'tool-faceSwap') {
      if (part.state === 'input-available') return (
        <div key={i} className="mt-4 bg-gray-900/60 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-sm">
          <div className="flex items-center space-x-2 text-gray-400">
            <Loader2 size={16} className="animate-spin" />
            <ImageIcon size={16} />
            <span className="text-sm font-medium">Swapping faces...</span>
          </div>
        </div>
      );
      if (part.state === 'output-available') return (
        <div key={i} className="mt-4 bg-gray-950/95 border border-gray-800/40 rounded-2xl p-4 backdrop-blur-xl shadow-lg">
          <div className="mb-3">
            <div className="flex items-center space-x-2 text-gray-300 mb-2">
              <ImageIcon size={16} />
              <span className="text-sm font-semibold">Face-Swap Result</span>
            </div>
            <img src={part.output.imageUrl} alt="Face-swapped" className="w-full rounded-xl border border-gray-700/30 shadow-lg" />
          </div>
        </div>
      );
      if (part.state === 'output-error') return (
        <div key={i} className="mt-4 bg-red-950/30 border border-red-500/20 rounded-xl p-3">
          <div className="flex items-center space-x-2 text-red-400 text-sm">
            <AlertCircle size={16} />
            <span>Face-Swap Error: {part.errorText}</span>
          </div>
        </div>
      );
      return null;
    }

    return null;
  };

  /* ------------------------------------------------------------------ */
  /*  4.  Message bubble wrapper (unchanged)                            */
  /* ------------------------------------------------------------------ */
  const MessageBubble = ({ message, isUser }: { message: any; isUser: boolean }) => (
    <div className={`flex items-start space-x-4 group ${isUser ? "flex-row-reverse space-x-reverse" : ""}`}>
      <div className={`flex-shrink-0 w-10 h-10 rounded-2xl flex items-center justify-center shadow-lg transition-all duration-300 group-hover:scale-110 ${isUser
          ? "bg-gradient-to-br from-gray-600 to-gray-700 shadow-gray-600/20"
          : "bg-gradient-to-br from-gray-800 to-gray-900 border border-gray-700/30 shadow-gray-900/20"
        }`}>
        {isUser ? (
          <User size={18} className="text-gray-200" />
        ) : (
          <Sparkles size={18} className="text-gray-300" />
        )}
      </div>

      <div className={`max-w-2xl ${isUser ? "items-end" : "items-start"} flex flex-col`}>
        <div className={`rounded-3xl px-6 py-4 transition-all duration-300 group-hover:shadow-lg ${isUser
            ? "bg-gradient-to-br from-gray-700 to-gray-800 text-gray-100 shadow-lg shadow-gray-700/10"
            : "bg-gray-950/95 border border-gray-800/40 text-gray-200 shadow-lg shadow-black/10 backdrop-blur-xl"
          }`}>
          <div className="text-sm leading-relaxed">
            {message.parts.map((part, i) => renderToolPart(part, i, message.id))}
          </div>
        </div>
        <div className="text-xs text-gray-500 mt-2 px-3 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
          {new Date(message.timestamp || Date.now()).toLocaleTimeString()}
        </div>
      </div>
    </div>
  );

  /* ------------------------------------------------------------------ */
  /*  5.  Sidebar (unchanged)                                           */
  /* ------------------------------------------------------------------ */
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const Sidebar = ({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) => {
    const sidebarItems = [
      { icon: Home, label: "Dashboard", path: "dashboard" },
      { icon: MessageSquare, label: "Chat", path: "googleandyoutubeads" },
      { icon: Settings2, label: "Settings", path: "settings" },
    ];
    const quickActions = [
      { icon: TrendingUp, label: "Keywords Finder", path: "keywordfinder", color: "text-gray-400 bg-gray-800/30" },
      { icon: Target, label: "Expired Domains", path: "expireddomain", color: "text-gray-400 bg-gray-800/20" },
      { icon: Zap, label: "Pricing", path: "pricing", color: "text-gray-400 bg-gray-800/40" },
    ];

    return (
      <>
        {isOpen && (
          <div className="lg:hidden fixed inset-0 bg-black/80 backdrop-blur-sm z-40 transition-opacity duration-300" onClick={onClose} />
        )}
        <div className={`fixed left-0 top-0 h-full w-80 bg-gray-950/98 border-r border-gray-800/30 backdrop-blur-xl z-50 transform transition-transform duration-300 ease-out ${isOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0"}`}>
          <div className="flex flex-col h-full">
            <div className="p-6 border-b border-gray-800/30">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-gray-600 to-gray-700 rounded-2xl flex items-center justify-center shadow-lg shadow-gray-600/20">
                    <Image src="/goblin.png" alt="Goblin Pro Logo" width={40} height={40} className="rounded-2xl" />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold text-gray-200">Goblin Pro</h2>
                    <div className="text-xs text-gray-500">AI-Ads Assistant</div>
                  </div>
                </div>
                <button onClick={onClose} className="lg:hidden p-2 text-gray-400 hover:text-gray-300 hover:bg-gray-900/50 rounded-lg transition-all duration-200">
                  <X size={18} />
                </button>
              </div>
            </div>

            <ScrollArea className="flex-1 px-4">
              <div className="py-4">
                <nav className="space-y-2">
                  {sidebarItems.map((item, index) => (
                    <Link href={`/${item.path}`} key={index} className="w-full flex items-center space-x-3 px-4 py-3 rounded-2xl text-sm font-medium transition-all duration-200 text-gray-400 hover:text-gray-300 hover:bg-gray-900/40 hover:border-gray-800/30 border border-transparent">
                      <item.icon size={18} />
                      <span>{item.label}</span>
                    </Link>
                  ))}
                </nav>

                <div className="mt-8">
                  <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-4 px-4">Quick Actions</h3>
                  <div className="space-y-2">
                    {quickActions.map((action, index) => (
                      <Link href={`/${action.path}`} key={index} className="w-full flex items-center space-x-3 px-4 py-3 rounded-2xl text-sm font-medium transition-all duration-200 text-gray-400 hover:bg-gray-900/40 hover:border-gray-800/30 border border-transparent">
                        <div className={`p-2 rounded-xl ${action.color} transition-all duration-200 group-hover:scale-110`}>
                          <action.icon size={14} />
                        </div>
                        <span>{action.label}</span>
                      </Link>
                    ))}
                  </div>
                </div>
              </div>
            </ScrollArea>

            <div className="p-4 border-t border-gray-800/30">
              <div className="bg-gradient-to-r from-gray-800/40 to-gray-700/40 border border-gray-700/30 rounded-2xl p-4">
                <div className="flex items-center space-x-2 mb-2">
                  <Star size={16} className="text-gray-400" />
                  <span className="text-sm font-semibold text-gray-300">Pro Features</span>
                </div>
                <p className="text-xs text-gray-500 mb-3">Unlock advanced AI capabilities and unlimited campaigns</p>
                <Link href='/pricing'>
                  <button className="w-full bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 py-2 px-4 rounded-xl text-sm font-medium hover:shadow-lg hover:shadow-gray-600/10 transition-all duration-200">
                    Upgrade Now
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  };

  /* ------------------------------------------------------------------ */
  /*  6.  Page layout (unchanged)                                       */
  /* ------------------------------------------------------------------ */
  return (
    <div className="flex h-screen bg-gray-950 text-gray-100 overflow-hidden">
      <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />

      <div className="flex-1 flex flex-col lg:ml-80 transition-all duration-300">
        <header className="border-b border-gray-800/30 bg-gray-950/98 backdrop-blur-xl">
          <div className="flex items-center justify-between px-6 py-4">
            <div className="flex items-center space-x-4">
              <button onClick={() => setSidebarOpen(true)} className="lg:hidden p-2 text-gray-400 hover:text-gray-300 hover:bg-gray-900/50 rounded-xl transition-all duration-200">
                <Menu size={20} />
              </button>

              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-gradient-to-br from-gray-600 to-gray-700 rounded-2xl flex items-center justify-center shadow-lg shadow-gray-600/20">
                  <Sparkles size={20} className="text-gray-200" />
                </div>
                <div className="hidden sm:block">
                  <h1 className="text-xl font-bold text-gray-200">AI Creator Studio</h1>
                  <div className="text-sm text-gray-500">Generate & Mint Creative Content</div>
                </div>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                <span className="text-sm text-green-400 font-medium">Online</span>
              </div>
            </div>
          </div>
        </header>

        <main className="flex-1 flex flex-col overflow-hidden">
          <ScrollArea className="flex-1">
            <div className="max-w-4xl mx-auto px-6 py-8">
              {messages.length === 0 && (
                <div className="text-center py-16">
                  <div className="w-20 h-20 bg-gradient-to-br from-gray-700 to-gray-800 rounded-3xl flex items-center justify-center mx-auto mb-6 shadow-2xl shadow-gray-700/20">
                    <Sparkles size={32} className="text-gray-300" />
                  </div>
                  <h2 className="text-2xl font-bold text-gray-200 mb-4">Create Amazing Content with AI</h2>
                  <p className="text-gray-400 mb-8 max-w-md mx-auto">
                    Generate images, videos, 3-D models, and music. Then mint them as NFTs!
                  </p>
                </div>
              )}

              <div className="space-y-8">
                {messages.map((msg) => (
                  <MessageBubble key={msg.id} message={msg} isUser={msg.role === 'user'} />
                ))}
              </div>
            </div>
          </ScrollArea>

          <div className="border-t border-gray-800/30 bg-gray-950/98 backdrop-blur-xl">
            <div className="max-w-4xl mx-auto px-6 py-6">
              <div className="relative">
                <div className="relative flex items-center">
                  <input
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder="Ask me anything, request an image, video, 3-D model, or music…"
                    className="w-full bg-gray-900/60 border border-gray-800/40 focus:border-gray-700/60 rounded-3xl px-6 py-4 pr-16 text-gray-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-700/30 transition-all duration-200 backdrop-blur-sm shadow-lg"
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        if (input.trim()) {
                          sendMessage({ text: input });
                          setInput('');
                        }
                      }
                    }}
                  />
                  <button
                    onClick={() => {
                      if (input.trim()) {
                        sendMessage({ text: input });
                        setInput('');
                      }
                    }}
                    disabled={!input.trim()}
                    className={`absolute right-2 p-3 rounded-2xl transition-all duration-200 shadow-lg ${
                      !input.trim()
                        ? "bg-gray-800/50 text-gray-500 cursor-not-allowed"
                        : "bg-gradient-to-r from-gray-600 to-gray-700 text-gray-100 hover:from-gray-500 hover:to-gray-600 shadow-gray-600/20 hover:shadow-gray-600/30 hover:scale-105"
                    }`}
                  >
                    <Send size={20} />
                  </button>
                </div>
              </div>

              <div className="flex items-center justify-between mt-4 text-xs text-gray-500">
                <div className="flex items-center space-x-4">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                    <span>AI Services Active</span>
                  </div>
                </div>
                <div className="hidden sm:block">Powered by advanced AI • Create & Mint NFTs</div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}